from selenium import webdriver
import unittest

class NewVisitorTest(unittest.TestCase):

    def setUp(self):
	self.browser = webdriver.Firefox()
	self.browser.implicitly_wait(3)

    def tearDown(self):
	self.browser.quit()

    def test_can_start_a_list_and_retrieve_it_later(self):
	# Tesla goes to check out the home page
	self.browser.get('http://localhost:7070')
	
	# He notices the title mentions To-Do
	self.assertIn('To-Do', self.browser.title)
	self.fail('Finish the test.')
	
	# He is invited to enter a ToDo item straight away.
	
	# He types 'Call Faraday' into text box
	
	# When he hits enter, the page updates, and now
	# lists '1: Call Faraday' as an item in a to-do list
	
	# There is still a test-box inviting him to enter
	# another item. He enters "Use that information" as an item to ToDo list
	
	# Page updates again and shows both the item in his ToDo list
	
	# He wonders whether site will still remember his list. He notices a
	# unique URL has been generated by the site. He visits the Url to find
	# his todo list is still there.
	
	# Satisfied he goes to sleep for the day.

if __name__ == '__main__':
    unittest.main()
